# Generated by Django 4.1.5 on 2023-01-18 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_user_profil_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profil_photo',
            field=models.ImageField(blank=True, default='', null=True, upload_to='uploads_images/', verbose_name='Photo_user'),
        ),
    ]
